server:
  port: 4000
https:
  port: 4001
  ssl:
    key-store: wx.wxhjic.com.jks
    key-store-password: 34xm5PU9
    key-password: 34xm5PU9
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  boot:
    admin:
      client:
        url:
          - http://172.19.242.52:10000
  data:
    mongodb:
      uri: mongodb://wxhjdb:123456@172.19.242.50:27017,172.19.242.52:27017/wxhj?replicaSet=replset&readPreference=secondaryPreferred&maxPoolSize=50&slaveOk=true
  redis:
    cluster:
      nodes:
        - 172.19.242.50:7001
        - 172.19.242.50:7002
        - 172.19.242.51:7001
        - 172.19.242.51:7002
        - 172.19.242.52:7001
        - 172.19.242.52:7002
    password: 123456
  zipkin:
    base-url: http://172.19.242.52:10010
    sleuth:
      sampler:
        probability: 1
    sender:
      type: web
  application:
    name: gatewayServer
  cloud:
    #    config:
    #      enabled: false
    zookeeper:
      connect-string: 172.19.242.50:2181,172.19.242.51:2181,172.19.242.52:2181
      discovery:
        register: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    platformServer:
      path: /platformServer/**
      serviceId: platformServer
    fileServer:
      path: /fileServer/**
      serviceId: fileServer
    appServer:
      path: /appServer/**
      serviceId: appServer
    accountServer:
      path: /accountServer/**
      serviceId: accountServer
logging:
  config: classpath:logback-spring-test.xml
wxhj:
  tokenfilter:
    web:
      matchingUrls:
        - /platformServer/**
      excludedPaths:
        - /platformServer/login
        - /platformServer/test
        - /platformServer/accountList
        - /platformServer/verificaImg
    attack-verification:
      matchingUrls:
        - /platformServer/**
      excludedPaths:
        - /platformServer/test
        - /platformServer/login
        - /platformServer/accountList
        - /platformServer/verificaImg
        - /platformServer/systemManage/account/faceRegisterBatch
    request-limit:
      matchingUrls :
        - /accountServer/**
      excludedPaths:
        - /accountServer/wechat/payResultNotify
    device:
      matching-urls:
        - /deviceServer/**
      excluded-paths:
        - /deviceServer/test
      md5-key: 52606F34C985403D850D411BCB600DCD
management:
  endpoints:
    web:
      exposure:
        include: '*'