server:
  port: 4000
https:
  port: 4001
  ssl:
    key-store: wx.wxhjic.com.jks
    key-store-password: 34xm5PU9
    key-password: 34xm5PU9
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  boot:
    admin:
      client:
        url:
          - http://172.19.242.210:10000
  data:
    mongodb:
      uri: mongodb://wxhjdb:123456@172.19.242.224:27017,172.19.242.225:27017,172.19.242.226:27017/wxhj?replicaSet=replset&readPreference=secondaryPreferred&maxPoolSize=50&slaveOk=true
  redis:
    cluster:
      nodes:
        - 172.19.242.225:7006
        - 172.19.242.225:7001
        - 172.19.242.225:7002
        - 172.19.242.225:7003
        - 172.19.242.225:7004
        - 172.19.242.225:7005
    password: 123456
  zipkin:
    base-url: http://172.19.242.210:10010
    sleuth:
      sampler:
        probability: 1
    sender:
      type: web
  application:
    name: gatewayServer
  cloud:
    zookeeper:
      connect-string: 172.19.242.224:2181,172.19.242.224:2182,172.19.242.224:2183
      discovery:
        register: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 12000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 15000
  routes:
    platformServer:
      path: /platformServer/**
      serviceId: platformServer
    fileServer:
      path: /fileServer/**
      serviceId: fileServer
    appServer:
      path: /appServer/**
      serviceId: appServer
logging:
  config: classpath:logback-spring.xml
wxhj:
  elasticsearch:
    host: 172.19.242.224
    port: 9200
    scheme: http
  tokenfilter:
    web:
      matchingUrls:
        - /platformServer/**
      excludedPaths:
        - /platformServer/login
        - /platformServer/test
        - /platformServer/accountList
        - /platformServer/verificaImg
#      md5-key: 52606F34C985403D850D411BCB600DCD
      md5-key: xhsgxxn
    attack-verification:
      matchingUrls:
        - /platformServer/**
      excludedPaths:
        - /platformServer/test
        - /platformServer/login
        - /platformServer/accountList
        - /platformServer/verificaImg
        - /platformServer/systemManage/account/faceRegisterBatch
    request-limit:
      matchingUrls:
        - /accountServer/**
      excludedPaths:
        - /accountServer/wechat/payResultNotify
    device:
      matching-urls:
        - /deviceServer/**
      excluded-paths:
        - /deviceServer/test
#      md5-key: 52606F34C985403D850D411BCB600DCD
      md5-key: xhsgxxn
    app:
      matching-urls:
        - /appServer/**
      excluded-paths:
        - /appServer/userOperate/accountLoginOrganize
        - /appServer//userOperate/accountLogin
#      md5-key: 52606F34C985403D850D411BCB600DCD
      md5-key: xhsgxxn
management:
  endpoints:
    web:
      exposure:
        include: '*'