server:
  port: 4050
spring:
  boot:
    admin:
      client:
        url:
        - http://172.19.242.217:10000
  data:
    mongodb:
        uri: mongodb://wxhjdb:123456@172.19.242.224:27017,172.19.242.225:27017,172.19.242.226:27017/wxhj?replicaSet=replset&readPreference=secondaryPreferred&maxPoolSize=50&slaveOk=true  
  application:
    name: fileServer
  cloud:
    zookeeper:
      connect-string: 172.19.242.224:2181,172.19.242.224:2182,172.19.242.224:2183
  zipkin:
    base-url: http://172.19.242.217:10010
    sleuth:
      sampler:
        probability: 1
    sender:
      type: web
wxhj:
  rocket:
    rocket-servers: 172.19.242.224:9876;172.19.242.225:9876
    rocket-group: fileServerGroup
management:
  endpoints:
    web:
      exposure:
        include: '*'