server:
  port: 4050
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  boot:
    admin:
      client:
        url:
        - http://172.19.242.210:10000
  data:
    mongodb:
        uri: mongodb://wxhjdb:123456@172.19.242.224:27017,172.19.242.225:27017,172.19.242.226:27017/wxhj?replicaSet=replset&readPreference=secondaryPreferred&maxPoolSize=50&slaveOk=true
  application:
    name: fileServer
  cloud:
    zookeeper:
#      connect-string: 127.0.0.1:2181
      connect-string: 172.19.242.224:2181,172.19.242.224:2182,172.19.242.224:2183
  redis:
    cluster:
      nodes:
      - 172.19.242.225:7006
      - 172.19.242.225:7001
      - 172.19.242.225:7002
      - 172.19.242.225:7003
      - 172.19.242.225:7004
      - 172.19.242.225:7005
    password: 123456
  zipkin:
    base-url: http://172.19.242.210:10010
    sleuth:
      sampler:
        probability: 1
    sender:
      type: web
logging:
  config: classpath:logback-spring.xml
wxhj:
  rocket:
    rocket-servers: 172.19.242.224:9876;172.19.242.225:9876
    rocket-group: fileServerGroup
  baidu:
    fileBucketName: burcket-dev1
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000