server:
  port: 10010
spring:
  cloud:
    zookeeper:
      enabled: true
      connect-string: zk-0.zk-hs.kube-main.svc.cluster.local:2181,zk-1.zk-hs.kube-main.svc.cluster.local:2181,zk-2.zk-hs.kube-main.svc.cluster.local:2181
      discovery:
        enabled: true
        register: true
  boot:
    admin:
      client:
        url:
        - http://10.96.10.185:10000
  application:
    name: zipkinServer
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: '*'