server:
  port: 10010
spring:
  cloud:
    zookeeper:
      enabled: true
      connect-string: 172.19.242.224:2181,172.19.242.224:2182,172.19.242.224:2183
      discovery:
        enabled: true
        register: true
  boot:
    admin:
      client:
        url:
        - http://172.19.242.210:10000
  application:
    name: zipkinServer
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: '*'