server:
  port: 10010
spring:
  cloud:
    zookeeper:
      enabled: true
      connect-string: 172.19.242.50:2181,172.19.242.51:2181,172.19.242.52:2181
      discovery:
        enabled: true
        register: true
  boot:
    admin:
      client:
        url:
        - http://172.19.242.52:10000
  application:
    name: zipkinServer
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: '*'