server:
  port: 10020
spring:
  cloud:
    zookeeper:
      connect-string: 172.19.242.224:2181,172.19.242.224:2182,172.19.242.224:2183
  application:
    name: hystrixServer
  boot:
    admin:
      client:
        url: http://172.19.242.210:10000
management:
  endpoints:
    web:
      exposure:
        include: "*"